apiVersion: v1
kind: Service
metadata:
  name: weather-forecast-service
spec:
  type: LoadBalancer
  selector:
    app: weather-forecast-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
